Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "public_network", use_dhcp_assigned_default_route: true
  config.vm.provision :shell, path: "init.sh"
  config.vm.provision :shell, path: "start.sh", privileged: false
end